name: 🐛 Bug Report
description: Suggest something
title: "Bug 🍭 "
labels: ["bug"]
body:
  - type: markdown
    value: |
        # Bug Report
  - type: textarea
    attributes:
      label: Bug
      description: Give me more informations about the bug you found
      placeholder: Describe the bug you found
    validations:
      required: true
