name: 🐞 Suggestion
description: Suggest something

labels: ["enhancement"]
body:
  - type: textarea
    attributes:
    label: Suggestion
    description: Explain what you are suggesting
    placeholder: Suggestion
    validations:
      required: true