name: 🐞 Suggestion
description: Suggest something
title: "Suggestion 🍭 <title>"

body:
  - type: textarea
    attributes:
    label: Suggestion
    description: Explain what you are suggesting
    placeholder: Suggestion
    validations:
      required: true