name: 🐞 Suggestion
description: Suggest something
title: "Suggestion 🍭 "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
    label: Suggestion
    description: Explain what you are suggesting
    placeholder: Suggestion