name: 🐞 Suggestion
description: Suggest something
title: "Suggestion 🍭 <title>"
labels: ["enhancement"]
body:
  - type: input
    attributes:
      label: Suggestion
      description: Explain what you are suggesting
      placeholder: Suggestion
      validations:
        required: true